// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/shipping.proto

package shippingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representasi tabel Shipments
type ShipmentDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId           string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CourierCode       string                 `protobuf:"bytes,3,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode       string                 `protobuf:"bytes,4,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,5,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ShippingCost      int64                  `protobuf:"varint,7,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	EstimatedDelivery *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShipmentDetail) Reset() {
	*x = ShipmentDetail{}
	mi := &file_proto_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentDetail) ProtoMessage() {}

func (x *ShipmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentDetail.ProtoReflect.Descriptor instead.
func (*ShipmentDetail) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShipmentDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentDetail) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipmentDetail) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *ShipmentDetail) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *ShipmentDetail) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *ShipmentDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentDetail) GetShippingCost() int64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *ShipmentDetail) GetEstimatedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

// 1. Calculate Cost
type ShippingCostRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginCityId      string                 `protobuf:"bytes,1,opt,name=origin_city_id,json=originCityId,proto3" json:"origin_city_id,omitempty"`
	DestinationCityId string                 `protobuf:"bytes,2,opt,name=destination_city_id,json=destinationCityId,proto3" json:"destination_city_id,omitempty"`
	TotalWeightG      int32                  `protobuf:"varint,3,opt,name=total_weight_g,json=totalWeightG,proto3" json:"total_weight_g,omitempty"`
	CourierCode       string                 `protobuf:"bytes,4,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode       string                 `protobuf:"bytes,5,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShippingCostRequest) Reset() {
	*x = ShippingCostRequest{}
	mi := &file_proto_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostRequest) ProtoMessage() {}

func (x *ShippingCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostRequest.ProtoReflect.Descriptor instead.
func (*ShippingCostRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingCostRequest) GetOriginCityId() string {
	if x != nil {
		return x.OriginCityId
	}
	return ""
}

func (x *ShippingCostRequest) GetDestinationCityId() string {
	if x != nil {
		return x.DestinationCityId
	}
	return ""
}

func (x *ShippingCostRequest) GetTotalWeightG() int32 {
	if x != nil {
		return x.TotalWeightG
	}
	return 0
}

func (x *ShippingCostRequest) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *ShippingCostRequest) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

type ShippingCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierCode   string                 `protobuf:"bytes,1,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode   string                 `protobuf:"bytes,2,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	Cost          int64                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	EstimatedTime string                 `protobuf:"bytes,4,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingCostResponse) Reset() {
	*x = ShippingCostResponse{}
	mi := &file_proto_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostResponse) ProtoMessage() {}

func (x *ShippingCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostResponse.ProtoReflect.Descriptor instead.
func (*ShippingCostResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingCostResponse) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *ShippingCostResponse) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *ShippingCostResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ShippingCostResponse) GetEstimatedTime() string {
	if x != nil {
		return x.EstimatedTime
	}
	return ""
}

// 2. Input Tracking Number
type InputTrackingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	CourierCode    string                 `protobuf:"bytes,3,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InputTrackingRequest) Reset() {
	*x = InputTrackingRequest{}
	mi := &file_proto_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputTrackingRequest) ProtoMessage() {}

func (x *InputTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputTrackingRequest.ProtoReflect.Descriptor instead.
func (*InputTrackingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *InputTrackingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InputTrackingRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *InputTrackingRequest) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

// 3. Get Status
type GetShipmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentStatusRequest) Reset() {
	*x = GetShipmentStatusRequest{}
	mi := &file_proto_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentStatusRequest) ProtoMessage() {}

func (x *GetShipmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_proto_shipping_proto protoreflect.FileDescriptor

const file_proto_shipping_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shipping.proto\x12\bshipping\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\x0eShipmentDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\fcourier_code\x18\x03 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x04 \x01(\tR\vserviceCode\x12'\n" +
	"\x0ftracking_number\x18\x05 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rshipping_cost\x18\a \x01(\x03R\fshippingCost\x12I\n" +
	"\x12estimated_delivery\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11estimatedDelivery\"\xd7\x01\n" +
	"\x13ShippingCostRequest\x12$\n" +
	"\x0eorigin_city_id\x18\x01 \x01(\tR\foriginCityId\x12.\n" +
	"\x13destination_city_id\x18\x02 \x01(\tR\x11destinationCityId\x12$\n" +
	"\x0etotal_weight_g\x18\x03 \x01(\x05R\ftotalWeightG\x12!\n" +
	"\fcourier_code\x18\x04 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x05 \x01(\tR\vserviceCode\"\x97\x01\n" +
	"\x14ShippingCostResponse\x12!\n" +
	"\fcourier_code\x18\x01 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x02 \x01(\tR\vserviceCode\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x03R\x04cost\x12%\n" +
	"\x0eestimated_time\x18\x04 \x01(\tR\restimatedTime\"}\n" +
	"\x14InputTrackingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12!\n" +
	"\fcourier_code\x18\x03 \x01(\tR\vcourierCode\"5\n" +
	"\x18GetShipmentStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId2\x85\x02\n" +
	"\x0fShippingService\x12N\n" +
	"\rCalculateCost\x12\x1d.shipping.ShippingCostRequest\x1a\x1e.shipping.ShippingCostResponse\x12O\n" +
	"\x13InputTrackingNumber\x12\x1e.shipping.InputTrackingRequest\x1a\x18.shipping.ShipmentDetail\x12Q\n" +
	"\x11GetShipmentStatus\x12\".shipping.GetShipmentStatusRequest\x1a\x18.shipping.ShipmentDetailB\"Z /internal/pb/shipping;shippingpbb\x06proto3"

var (
	file_proto_shipping_proto_rawDescOnce sync.Once
	file_proto_shipping_proto_rawDescData []byte
)

func file_proto_shipping_proto_rawDescGZIP() []byte {
	file_proto_shipping_proto_rawDescOnce.Do(func() {
		file_proto_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipping_proto_rawDesc), len(file_proto_shipping_proto_rawDesc)))
	})
	return file_proto_shipping_proto_rawDescData
}

var file_proto_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_shipping_proto_goTypes = []any{
	(*ShipmentDetail)(nil),           // 0: shipping.ShipmentDetail
	(*ShippingCostRequest)(nil),      // 1: shipping.ShippingCostRequest
	(*ShippingCostResponse)(nil),     // 2: shipping.ShippingCostResponse
	(*InputTrackingRequest)(nil),     // 3: shipping.InputTrackingRequest
	(*GetShipmentStatusRequest)(nil), // 4: shipping.GetShipmentStatusRequest
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_proto_shipping_proto_depIdxs = []int32{
	5, // 0: shipping.ShipmentDetail.estimated_delivery:type_name -> google.protobuf.Timestamp
	1, // 1: shipping.ShippingService.CalculateCost:input_type -> shipping.ShippingCostRequest
	3, // 2: shipping.ShippingService.InputTrackingNumber:input_type -> shipping.InputTrackingRequest
	4, // 3: shipping.ShippingService.GetShipmentStatus:input_type -> shipping.GetShipmentStatusRequest
	2, // 4: shipping.ShippingService.CalculateCost:output_type -> shipping.ShippingCostResponse
	0, // 5: shipping.ShippingService.InputTrackingNumber:output_type -> shipping.ShipmentDetail
	0, // 6: shipping.ShippingService.GetShipmentStatus:output_type -> shipping.ShipmentDetail
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shipping_proto_init() }
func file_proto_shipping_proto_init() {
	if File_proto_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipping_proto_rawDesc), len(file_proto_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipping_proto_goTypes,
		DependencyIndexes: file_proto_shipping_proto_depIdxs,
		MessageInfos:      file_proto_shipping_proto_msgTypes,
	}.Build()
	File_proto_shipping_proto = out.File
	file_proto_shipping_proto_goTypes = nil
	file_proto_shipping_proto_depIdxs = nil
}
