// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/shipping.proto

package shippingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representasi tabel Shipments
type ShipmentDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId           string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CourierCode       string                 `protobuf:"bytes,3,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode       string                 `protobuf:"bytes,4,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,5,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ShippingCost      int64                  `protobuf:"varint,7,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	EstimatedDelivery *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShipmentDetail) Reset() {
	*x = ShipmentDetail{}
	mi := &file_proto_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentDetail) ProtoMessage() {}

func (x *ShipmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentDetail.ProtoReflect.Descriptor instead.
func (*ShipmentDetail) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShipmentDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentDetail) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipmentDetail) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *ShipmentDetail) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *ShipmentDetail) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *ShipmentDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentDetail) GetShippingCost() int64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *ShipmentDetail) GetEstimatedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

// 1. Calculate Cost
type ShippingCostOfferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginCity      string                 `protobuf:"bytes,1,opt,name=origin_city,json=originCity,proto3" json:"origin_city,omitempty"`
	DestinationCity string                 `protobuf:"bytes,2,opt,name=destination_city,json=destinationCity,proto3" json:"destination_city,omitempty"`
	TotalWeightG    int32                  `protobuf:"varint,3,opt,name=total_weight_g,json=totalWeightG,proto3" json:"total_weight_g,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShippingCostOfferRequest) Reset() {
	*x = ShippingCostOfferRequest{}
	mi := &file_proto_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostOfferRequest) ProtoMessage() {}

func (x *ShippingCostOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostOfferRequest.ProtoReflect.Descriptor instead.
func (*ShippingCostOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingCostOfferRequest) GetOriginCity() string {
	if x != nil {
		return x.OriginCity
	}
	return ""
}

func (x *ShippingCostOfferRequest) GetDestinationCity() string {
	if x != nil {
		return x.DestinationCity
	}
	return ""
}

func (x *ShippingCostOfferRequest) GetTotalWeightG() int32 {
	if x != nil {
		return x.TotalWeightG
	}
	return 0
}

type ShippingOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courier       string                 `protobuf:"bytes,1,opt,name=courier,proto3" json:"courier,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Cost          int64                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	EstimatedDays int32                  `protobuf:"varint,4,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingOption) Reset() {
	*x = ShippingOption{}
	mi := &file_proto_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingOption) ProtoMessage() {}

func (x *ShippingOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingOption.ProtoReflect.Descriptor instead.
func (*ShippingOption) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingOption) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *ShippingOption) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ShippingOption) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ShippingOption) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

type ShippingCostOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*ShippingOption      `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingCostOfferResponse) Reset() {
	*x = ShippingCostOfferResponse{}
	mi := &file_proto_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostOfferResponse) ProtoMessage() {}

func (x *ShippingCostOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostOfferResponse.ProtoReflect.Descriptor instead.
func (*ShippingCostOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *ShippingCostOfferResponse) GetOptions() []*ShippingOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ShippingCostRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginCity      string                 `protobuf:"bytes,1,opt,name=origin_city,json=originCity,proto3" json:"origin_city,omitempty"`
	DestinationCity string                 `protobuf:"bytes,2,opt,name=destination_city,json=destinationCity,proto3" json:"destination_city,omitempty"`
	TotalWeightG    int32                  `protobuf:"varint,3,opt,name=total_weight_g,json=totalWeightG,proto3" json:"total_weight_g,omitempty"`
	CourierCode     string                 `protobuf:"bytes,4,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode     string                 `protobuf:"bytes,5,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShippingCostRequest) Reset() {
	*x = ShippingCostRequest{}
	mi := &file_proto_shipping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostRequest) ProtoMessage() {}

func (x *ShippingCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostRequest.ProtoReflect.Descriptor instead.
func (*ShippingCostRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{4}
}

func (x *ShippingCostRequest) GetOriginCity() string {
	if x != nil {
		return x.OriginCity
	}
	return ""
}

func (x *ShippingCostRequest) GetDestinationCity() string {
	if x != nil {
		return x.DestinationCity
	}
	return ""
}

func (x *ShippingCostRequest) GetTotalWeightG() int32 {
	if x != nil {
		return x.TotalWeightG
	}
	return 0
}

func (x *ShippingCostRequest) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *ShippingCostRequest) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

type ShippingCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierCode   string                 `protobuf:"bytes,1,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode   string                 `protobuf:"bytes,2,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	Cost          int64                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	EstimatedTime string                 `protobuf:"bytes,4,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingCostResponse) Reset() {
	*x = ShippingCostResponse{}
	mi := &file_proto_shipping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingCostResponse) ProtoMessage() {}

func (x *ShippingCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingCostResponse.ProtoReflect.Descriptor instead.
func (*ShippingCostResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{5}
}

func (x *ShippingCostResponse) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *ShippingCostResponse) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *ShippingCostResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ShippingCostResponse) GetEstimatedTime() string {
	if x != nil {
		return x.EstimatedTime
	}
	return ""
}

// 2. Get Shipment
type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_proto_shipping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{6}
}

func (x *GetShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 3. Create Shipment
type CreateShipmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CourierCode    string                 `protobuf:"bytes,2,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode    string                 `protobuf:"bytes,3,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,4,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	ShippingCost   int64                  `protobuf:"varint,5,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_proto_shipping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipping_proto_rawDescGZIP(), []int{7}
}

func (x *CreateShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShipmentRequest) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *CreateShipmentRequest) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *CreateShipmentRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateShipmentRequest) GetShippingCost() int64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

var File_proto_shipping_proto protoreflect.FileDescriptor

const file_proto_shipping_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shipping.proto\x12\bshipping\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\x0eShipmentDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\fcourier_code\x18\x03 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x04 \x01(\tR\vserviceCode\x12'\n" +
	"\x0ftracking_number\x18\x05 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rshipping_cost\x18\a \x01(\x03R\fshippingCost\x12I\n" +
	"\x12estimated_delivery\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11estimatedDelivery\"\x8c\x01\n" +
	"\x18ShippingCostOfferRequest\x12\x1f\n" +
	"\vorigin_city\x18\x01 \x01(\tR\n" +
	"originCity\x12)\n" +
	"\x10destination_city\x18\x02 \x01(\tR\x0fdestinationCity\x12$\n" +
	"\x0etotal_weight_g\x18\x03 \x01(\x05R\ftotalWeightG\"\x7f\n" +
	"\x0eShippingOption\x12\x18\n" +
	"\acourier\x18\x01 \x01(\tR\acourier\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x03R\x04cost\x12%\n" +
	"\x0eestimated_days\x18\x04 \x01(\x05R\restimatedDays\"O\n" +
	"\x19ShippingCostOfferResponse\x122\n" +
	"\aoptions\x18\x01 \x03(\v2\x18.shipping.ShippingOptionR\aoptions\"\xcd\x01\n" +
	"\x13ShippingCostRequest\x12\x1f\n" +
	"\vorigin_city\x18\x01 \x01(\tR\n" +
	"originCity\x12)\n" +
	"\x10destination_city\x18\x02 \x01(\tR\x0fdestinationCity\x12$\n" +
	"\x0etotal_weight_g\x18\x03 \x01(\x05R\ftotalWeightG\x12!\n" +
	"\fcourier_code\x18\x04 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x05 \x01(\tR\vserviceCode\"\x97\x01\n" +
	"\x14ShippingCostResponse\x12!\n" +
	"\fcourier_code\x18\x01 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x02 \x01(\tR\vserviceCode\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x03R\x04cost\x12%\n" +
	"\x0eestimated_time\x18\x04 \x01(\tR\restimatedTime\"/\n" +
	"\x12GetShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xc6\x01\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\fcourier_code\x18\x02 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x03 \x01(\tR\vserviceCode\x12'\n" +
	"\x0ftracking_number\x18\x04 \x01(\tR\x0etrackingNumber\x12#\n" +
	"\rshipping_cost\x18\x05 \x01(\x03R\fshippingCost2\xd0\x02\n" +
	"\x0fShippingService\x12\\\n" +
	"\x11OfferShippingCost\x12\".shipping.ShippingCostOfferRequest\x1a#.shipping.ShippingCostOfferResponse\x12S\n" +
	"\x12CalculateFinalCost\x12\x1d.shipping.ShippingCostRequest\x1a\x1e.shipping.ShippingCostResponse\x12E\n" +
	"\vGetShipment\x12\x1c.shipping.GetShipmentRequest\x1a\x18.shipping.ShipmentDetail\x12C\n" +
	"\x06Create\x12\x1f.shipping.CreateShipmentRequest\x1a\x18.shipping.ShipmentDetailB\"Z /internal/pb/shipping;shippingpbb\x06proto3"

var (
	file_proto_shipping_proto_rawDescOnce sync.Once
	file_proto_shipping_proto_rawDescData []byte
)

func file_proto_shipping_proto_rawDescGZIP() []byte {
	file_proto_shipping_proto_rawDescOnce.Do(func() {
		file_proto_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipping_proto_rawDesc), len(file_proto_shipping_proto_rawDesc)))
	})
	return file_proto_shipping_proto_rawDescData
}

var file_proto_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_shipping_proto_goTypes = []any{
	(*ShipmentDetail)(nil),            // 0: shipping.ShipmentDetail
	(*ShippingCostOfferRequest)(nil),  // 1: shipping.ShippingCostOfferRequest
	(*ShippingOption)(nil),            // 2: shipping.ShippingOption
	(*ShippingCostOfferResponse)(nil), // 3: shipping.ShippingCostOfferResponse
	(*ShippingCostRequest)(nil),       // 4: shipping.ShippingCostRequest
	(*ShippingCostResponse)(nil),      // 5: shipping.ShippingCostResponse
	(*GetShipmentRequest)(nil),        // 6: shipping.GetShipmentRequest
	(*CreateShipmentRequest)(nil),     // 7: shipping.CreateShipmentRequest
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_proto_shipping_proto_depIdxs = []int32{
	8, // 0: shipping.ShipmentDetail.estimated_delivery:type_name -> google.protobuf.Timestamp
	2, // 1: shipping.ShippingCostOfferResponse.options:type_name -> shipping.ShippingOption
	1, // 2: shipping.ShippingService.OfferShippingCost:input_type -> shipping.ShippingCostOfferRequest
	4, // 3: shipping.ShippingService.CalculateFinalCost:input_type -> shipping.ShippingCostRequest
	6, // 4: shipping.ShippingService.GetShipment:input_type -> shipping.GetShipmentRequest
	7, // 5: shipping.ShippingService.Create:input_type -> shipping.CreateShipmentRequest
	3, // 6: shipping.ShippingService.OfferShippingCost:output_type -> shipping.ShippingCostOfferResponse
	5, // 7: shipping.ShippingService.CalculateFinalCost:output_type -> shipping.ShippingCostResponse
	0, // 8: shipping.ShippingService.GetShipment:output_type -> shipping.ShipmentDetail
	0, // 9: shipping.ShippingService.Create:output_type -> shipping.ShipmentDetail
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shipping_proto_init() }
func file_proto_shipping_proto_init() {
	if File_proto_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipping_proto_rawDesc), len(file_proto_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipping_proto_goTypes,
		DependencyIndexes: file_proto_shipping_proto_depIdxs,
		MessageInfos:      file_proto_shipping_proto_msgTypes,
	}.Build()
	File_proto_shipping_proto = out.File
	file_proto_shipping_proto_goTypes = nil
	file_proto_shipping_proto_depIdxs = nil
}
