syntax = "proto3";

package inventory;

option go_package = "/internal/pb/inventory;inventorypb";

import "google/protobuf/empty.proto";

service InventoryService {
  rpc CreateStock(CreateStockRequest) returns (StockCount);
  rpc CheckStock(CheckStockRequest) returns (StockCount);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
  rpc UpdateStock(UpdateStockRequest) returns (StockCount);
  rpc ReleaseStock(ReleaseStockRequest) returns (google.protobuf.Empty);
}

// --- Message Definitions ---

message CheckStockRequest {
  string product_id = 1;
}

message StockCount {
  string product_id = 1;
  int32 total_stock = 2;
}

// Model item untuk request stok
message StockItem {
  string product_id = 1;
  int32 quantity = 2;
}

// Create Stock from New Product
message CreateStockRequest {
   string product_id = 1;
   int32 quantity = 2;
}

// Reserve Stock
message ReserveStockRequest {
  string order_id = 1; 
  repeated StockItem items = 2;
}

message ReserveStockResponse {
  repeated string out_of_stock_product_ids = 2; 
}

// Update Stock
message UpdateStockRequest {
  string product_id = 1;
  int32 quantity = 2;
}

// Release Stock (Rollback mechanism)
message ReleaseStockRequest {
  string order_id = 1;
  string action = 2;
}