// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_PENDING   OrderStatus = 0 // Menunggu Pembayaran
	OrderStatus_PAID      OrderStatus = 1 // Sudah dibayar, menunggu konfirmasi/packing
	OrderStatus_PROCESSED OrderStatus = 2 // Sedang dipacking
	OrderStatus_SHIPPED   OrderStatus = 3 // Sudah diserahkan ke kurir
	OrderStatus_DELIVERED OrderStatus = 4 // Sampai di tujuan
	OrderStatus_CANCELLED OrderStatus = 5 // Dibatalkan user/admin
	OrderStatus_FAILED    OrderStatus = 6 // Pembayaran gagal/expired
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "PENDING",
		1: "PAID",
		2: "PROCESSED",
		3: "SHIPPED",
		4: "DELIVERED",
		5: "CANCELLED",
		6: "FAILED",
	}
	OrderStatus_value = map[string]int32{
		"PENDING":   0,
		"PAID":      1,
		"PROCESSED": 2,
		"SHIPPED":   3,
		"DELIVERED": 4,
		"CANCELLED": 5,
		"FAILED":    6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

// Representasi Snapshot Alamat (JSONB di DB)
type AddressSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	ZipCode       string                 `protobuf:"bytes,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	ReceiverName  string                 `protobuf:"bytes,5,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone string                 `protobuf:"bytes,6,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressSnapshot) Reset() {
	*x = AddressSnapshot{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSnapshot) ProtoMessage() {}

func (x *AddressSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSnapshot.ProtoReflect.Descriptor instead.
func (*AddressSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *AddressSnapshot) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AddressSnapshot) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressSnapshot) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressSnapshot) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *AddressSnapshot) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *AddressSnapshot) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

// Representasi Item dalam Order
type OrderItem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity  int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Snapshot Data
	ProductNameSnapshot      string `protobuf:"bytes,4,opt,name=product_name_snapshot,json=productNameSnapshot,proto3" json:"product_name_snapshot,omitempty"`
	ProductThumbnailSnapshot string `protobuf:"bytes,5,opt,name=product_thumbnail_snapshot,json=productThumbnailSnapshot,proto3" json:"product_thumbnail_snapshot,omitempty"`
	ProductPriceSnapshot     int64  `protobuf:"varint,6,opt,name=product_price_snapshot,json=productPriceSnapshot,proto3" json:"product_price_snapshot,omitempty"`
	ProductWeightSnapshot    int32  `protobuf:"varint,7,opt,name=product_weight_snapshot,json=productWeightSnapshot,proto3" json:"product_weight_snapshot,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetProductNameSnapshot() string {
	if x != nil {
		return x.ProductNameSnapshot
	}
	return ""
}

func (x *OrderItem) GetProductThumbnailSnapshot() string {
	if x != nil {
		return x.ProductThumbnailSnapshot
	}
	return ""
}

func (x *OrderItem) GetProductPriceSnapshot() int64 {
	if x != nil {
		return x.ProductPriceSnapshot
	}
	return 0
}

func (x *OrderItem) GetProductWeightSnapshot() int32 {
	if x != nil {
		return x.ProductWeightSnapshot
	}
	return 0
}

// Representasi Order Utama
type OrderDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	TotalAmount     int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ShippingCost    int64                  `protobuf:"varint,5,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	ShippingAddress *AddressSnapshot       `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	// Info Pengiriman
	ShippingCourier string                 `protobuf:"bytes,7,opt,name=shipping_courier,json=shippingCourier,proto3" json:"shipping_courier,omitempty"`
	ShippingService string                 `protobuf:"bytes,8,opt,name=shipping_service,json=shippingService,proto3" json:"shipping_service,omitempty"`
	TrackingNumber  string                 `protobuf:"bytes,9,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderDetail) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *OrderDetail) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderDetail) GetShippingCost() int64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *OrderDetail) GetShippingAddress() *AddressSnapshot {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *OrderDetail) GetShippingCourier() string {
	if x != nil {
		return x.ShippingCourier
	}
	return ""
}

func (x *OrderDetail) GetShippingService() string {
	if x != nil {
		return x.ShippingService
	}
	return ""
}

func (x *OrderDetail) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *OrderDetail) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 1. Get Order History
type GetOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	StatusFilter  OrderStatus            `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3,enum=order.OrderStatus" json:"status_filter,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderHistoryRequest) Reset() {
	*x = GetOrderHistoryRequest{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryRequest) ProtoMessage() {}

func (x *GetOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrderHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrderHistoryRequest) GetStatusFilter() OrderStatus {
	if x != nil {
		return x.StatusFilter
	}
	return OrderStatus_PENDING
}

func (x *GetOrderHistoryRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type OrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderDetail         `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderList) GetOrders() []*OrderDetail {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrderList) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *OrderList) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

// 2. Get Order Detail
type GetOrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailRequest) Reset() {
	*x = GetOrderDetailRequest{}
	mi := &file_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailRequest) ProtoMessage() {}

func (x *GetOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderDetailRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderDetailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 3. Checkout
type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CourierCode   string                 `protobuf:"bytes,3,opt,name=courier_code,json=courierCode,proto3" json:"courier_code,omitempty"`
	ServiceCode   string                 `protobuf:"bytes,4,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	ProductIds    []string               `protobuf:"bytes,5,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckoutRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckoutRequest) GetCourierCode() string {
	if x != nil {
		return x.CourierCode
	}
	return ""
}

func (x *CheckoutRequest) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *CheckoutRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PaymentToken  string                 `protobuf:"bytes,3,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ExpiryTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *CheckoutResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CheckoutResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CheckoutResponse) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *CheckoutResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CheckoutResponse) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

// 4. Admin Filter
type AdminFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	DateStart     string                 `protobuf:"bytes,5,opt,name=date_start,json=dateStart,proto3" json:"date_start,omitempty"`
	DateEnd       string                 `protobuf:"bytes,6,opt,name=date_end,json=dateEnd,proto3" json:"date_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFilterRequest) Reset() {
	*x = AdminFilterRequest{}
	mi := &file_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFilterRequest) ProtoMessage() {}

func (x *AdminFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFilterRequest.ProtoReflect.Descriptor instead.
func (*AdminFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{8}
}

func (x *AdminFilterRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminFilterRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminFilterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminFilterRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_PENDING
}

func (x *AdminFilterRequest) GetDateStart() string {
	if x != nil {
		return x.DateStart
	}
	return ""
}

func (x *AdminFilterRequest) GetDateEnd() string {
	if x != nil {
		return x.DateEnd
	}
	return ""
}

// 5. Update Status
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus     OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=order.OrderStatus" json:"new_status,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"` // Reason for cancellation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateStatusRequest) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_PENDING
}

func (x *UpdateStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type OrderUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentStatus OrderStatus            `protobuf:"varint,3,opt,name=current_status,json=currentStatus,proto3,enum=order.OrderStatus" json:"current_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateResponse) Reset() {
	*x = OrderUpdateResponse{}
	mi := &file_proto_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateResponse) ProtoMessage() {}

func (x *OrderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateResponse.ProtoReflect.Descriptor instead.
func (*OrderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OrderUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrderUpdateResponse) GetCurrentStatus() OrderStatus {
	if x != nil {
		return x.CurrentStatus
	}
	return OrderStatus_PENDING
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\x0fAddressSnapshot\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\tR\azipCode\x12#\n" +
	"\rreceiver_name\x18\x05 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x06 \x01(\tR\rreceiverPhone\"\xb6\x02\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x122\n" +
	"\x15product_name_snapshot\x18\x04 \x01(\tR\x13productNameSnapshot\x12<\n" +
	"\x1aproduct_thumbnail_snapshot\x18\x05 \x01(\tR\x18productThumbnailSnapshot\x124\n" +
	"\x16product_price_snapshot\x18\x06 \x01(\x03R\x14productPriceSnapshot\x126\n" +
	"\x17product_weight_snapshot\x18\a \x01(\x05R\x15productWeightSnapshot\"\xcf\x03\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12#\n" +
	"\rshipping_cost\x18\x05 \x01(\x03R\fshippingCost\x12A\n" +
	"\x10shipping_address\x18\x06 \x01(\v2\x16.order.AddressSnapshotR\x0fshippingAddress\x12)\n" +
	"\x10shipping_courier\x18\a \x01(\tR\x0fshippingCourier\x12)\n" +
	"\x10shipping_service\x18\b \x01(\tR\x0fshippingService\x12'\n" +
	"\x0ftracking_number\x18\t \x01(\tR\x0etrackingNumber\x12&\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x10.order.OrderItemR\x05items\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa8\x01\n" +
	"\x16GetOrderHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x127\n" +
	"\rstatus_filter\x18\x04 \x01(\x0e2\x12.order.OrderStatusR\fstatusFilter\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\"{\n" +
	"\tOrderList\x12*\n" +
	"\x06orders\x18\x01 \x03(\v2\x12.order.OrderDetailR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\"K\n" +
	"\x15GetOrderDetailRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xab\x01\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fcourier_code\x18\x03 \x01(\tR\vcourierCode\x12!\n" +
	"\fservice_code\x18\x04 \x01(\tR\vserviceCode\x12\x1f\n" +
	"\vproduct_ids\x18\x05 \x03(\tR\n" +
	"productIds\"\xd3\x01\n" +
	"\x10CheckoutResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\x12#\n" +
	"\rpayment_token\x18\x03 \x01(\tR\fpaymentToken\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12;\n" +
	"\vexpiry_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryTime\"\xbd\x01\n" +
	"\x12AdminFilterRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"date_start\x18\x05 \x01(\tR\tdateStart\x12\x19\n" +
	"\bdate_end\x18\x06 \x01(\tR\adateEnd\"y\n" +
	"\x13UpdateStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x121\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\tnewStatus\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"\x84\x01\n" +
	"\x13OrderUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x0ecurrent_status\x18\x03 \x01(\x0e2\x12.order.OrderStatusR\rcurrentStatus*j\n" +
	"\vOrderStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\b\n" +
	"\x04PAID\x10\x01\x12\r\n" +
	"\tPROCESSED\x10\x02\x12\v\n" +
	"\aSHIPPED\x10\x03\x12\r\n" +
	"\tDELIVERED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x062\xdd\x02\n" +
	"\fOrderService\x12B\n" +
	"\x0fGetOrderHistory\x12\x1d.order.GetOrderHistoryRequest\x1a\x10.order.OrderList\x12B\n" +
	"\x0eGetOrderDetail\x12\x1c.order.GetOrderDetailRequest\x1a\x12.order.OrderDetail\x12;\n" +
	"\bCheckout\x12\x16.order.CheckoutRequest\x1a\x17.order.CheckoutResponse\x12;\n" +
	"\fGetAllOrders\x12\x19.order.AdminFilterRequest\x1a\x10.order.OrderList\x12K\n" +
	"\x11UpdateOrderStatus\x12\x1a.order.UpdateStatusRequest\x1a\x1a.order.OrderUpdateResponseB\x1cZ\x1a/internal/pb/order;orderpbb\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_order_proto_goTypes = []any{
	(OrderStatus)(0),               // 0: order.OrderStatus
	(*AddressSnapshot)(nil),        // 1: order.AddressSnapshot
	(*OrderItem)(nil),              // 2: order.OrderItem
	(*OrderDetail)(nil),            // 3: order.OrderDetail
	(*GetOrderHistoryRequest)(nil), // 4: order.GetOrderHistoryRequest
	(*OrderList)(nil),              // 5: order.OrderList
	(*GetOrderDetailRequest)(nil),  // 6: order.GetOrderDetailRequest
	(*CheckoutRequest)(nil),        // 7: order.CheckoutRequest
	(*CheckoutResponse)(nil),       // 8: order.CheckoutResponse
	(*AdminFilterRequest)(nil),     // 9: order.AdminFilterRequest
	(*UpdateStatusRequest)(nil),    // 10: order.UpdateStatusRequest
	(*OrderUpdateResponse)(nil),    // 11: order.OrderUpdateResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_proto_order_proto_depIdxs = []int32{
	0,  // 0: order.OrderDetail.status:type_name -> order.OrderStatus
	1,  // 1: order.OrderDetail.shipping_address:type_name -> order.AddressSnapshot
	2,  // 2: order.OrderDetail.items:type_name -> order.OrderItem
	12, // 3: order.OrderDetail.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: order.GetOrderHistoryRequest.status_filter:type_name -> order.OrderStatus
	3,  // 5: order.OrderList.orders:type_name -> order.OrderDetail
	12, // 6: order.CheckoutResponse.expiry_time:type_name -> google.protobuf.Timestamp
	0,  // 7: order.AdminFilterRequest.status:type_name -> order.OrderStatus
	0,  // 8: order.UpdateStatusRequest.new_status:type_name -> order.OrderStatus
	0,  // 9: order.OrderUpdateResponse.current_status:type_name -> order.OrderStatus
	4,  // 10: order.OrderService.GetOrderHistory:input_type -> order.GetOrderHistoryRequest
	6,  // 11: order.OrderService.GetOrderDetail:input_type -> order.GetOrderDetailRequest
	7,  // 12: order.OrderService.Checkout:input_type -> order.CheckoutRequest
	9,  // 13: order.OrderService.GetAllOrders:input_type -> order.AdminFilterRequest
	10, // 14: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateStatusRequest
	5,  // 15: order.OrderService.GetOrderHistory:output_type -> order.OrderList
	3,  // 16: order.OrderService.GetOrderDetail:output_type -> order.OrderDetail
	8,  // 17: order.OrderService.Checkout:output_type -> order.CheckoutResponse
	5,  // 18: order.OrderService.GetAllOrders:output_type -> order.OrderList
	11, // 19: order.OrderService.UpdateOrderStatus:output_type -> order.OrderUpdateResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		EnumInfos:         file_proto_order_proto_enumTypes,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
