syntax = "proto3";

package shipping;

option go_package = "/internal/pb/shipping;shippingpb";

import "google/protobuf/timestamp.proto";

service ShippingService {
  rpc OfferShippingCost(ShippingCostOfferRequest) returns (ShippingCostOfferResponse);
  rpc CalculateFinalCost(ShippingCostRequest) returns (ShippingCostResponse);
  rpc GetShipment(GetShipmentRequest) returns (ShipmentDetail);
  rpc Create(CreateShipmentRequest) returns (ShipmentDetail);
}

// --- Message Definitions ---

// Representasi tabel Shipments
message ShipmentDetail {
  string id = 1;
  string order_id = 2;
  string courier_code = 3; 
  string service_code = 4;   
  string tracking_number = 5;
  string status = 6;          
  int64 shipping_cost = 7;
  google.protobuf.Timestamp estimated_delivery = 8;
}

// 1. Calculate Cost
message ShippingCostOfferRequest {
  string origin_city = 1;     
  string destination_city = 2; 
  int32 total_weight_g = 3;  
}

message ShippingOption {
  string courier = 1;        
  string service = 2;         
  int64 cost = 3;              
  int32 estimated_days = 4;  
}

message ShippingCostOfferResponse {
  repeated ShippingOption options = 1;
}

message ShippingCostRequest {
  string origin_city = 1;     
  string destination_city = 2; 
  int32 total_weight_g = 3;       
  string courier_code = 4;      
  string service_code = 5;      
}

message ShippingCostResponse {
  string courier_code = 1;
  string service_code = 2;
  int64 cost = 3;
  string estimated_time = 4; 
}


// 2. Get Shipment
message GetShipmentRequest {
  string order_id = 1;
}

// 3. Create Shipment
message CreateShipmentRequest {
  string order_id = 1;
  string courier_code = 2;
  string service_code = 3;
  string tracking_number = 4;
  int64 shipping_cost = 5;
}