// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/shipping.proto

package shippingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShippingService_CalculateCost_FullMethodName       = "/shipping.ShippingService/CalculateCost"
	ShippingService_InputTrackingNumber_FullMethodName = "/shipping.ShippingService/InputTrackingNumber"
	ShippingService_GetShipmentStatus_FullMethodName   = "/shipping.ShippingService/GetShipmentStatus"
	ShippingService_Create_FullMethodName              = "/shipping.ShippingService/Create"
)

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShippingServiceClient interface {
	CalculateCost(ctx context.Context, in *ShippingCostRequest, opts ...grpc.CallOption) (*ShippingCostResponse, error)
	InputTrackingNumber(ctx context.Context, in *InputTrackingRequest, opts ...grpc.CallOption) (*ShipmentDetail, error)
	GetShipmentStatus(ctx context.Context, in *GetShipmentStatusRequest, opts ...grpc.CallOption) (*ShipmentDetail, error)
	Create(ctx context.Context, in *CreateShipmentRequest, opts ...grpc.CallOption) (*ShipmentDetail, error)
}

type shippingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShippingServiceClient(cc grpc.ClientConnInterface) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CalculateCost(ctx context.Context, in *ShippingCostRequest, opts ...grpc.CallOption) (*ShippingCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShippingCostResponse)
	err := c.cc.Invoke(ctx, ShippingService_CalculateCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) InputTrackingNumber(ctx context.Context, in *InputTrackingRequest, opts ...grpc.CallOption) (*ShipmentDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentDetail)
	err := c.cc.Invoke(ctx, ShippingService_InputTrackingNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetShipmentStatus(ctx context.Context, in *GetShipmentStatusRequest, opts ...grpc.CallOption) (*ShipmentDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentDetail)
	err := c.cc.Invoke(ctx, ShippingService_GetShipmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) Create(ctx context.Context, in *CreateShipmentRequest, opts ...grpc.CallOption) (*ShipmentDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipmentDetail)
	err := c.cc.Invoke(ctx, ShippingService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
// All implementations must embed UnimplementedShippingServiceServer
// for forward compatibility.
type ShippingServiceServer interface {
	CalculateCost(context.Context, *ShippingCostRequest) (*ShippingCostResponse, error)
	InputTrackingNumber(context.Context, *InputTrackingRequest) (*ShipmentDetail, error)
	GetShipmentStatus(context.Context, *GetShipmentStatusRequest) (*ShipmentDetail, error)
	Create(context.Context, *CreateShipmentRequest) (*ShipmentDetail, error)
	mustEmbedUnimplementedShippingServiceServer()
}

// UnimplementedShippingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShippingServiceServer struct{}

func (UnimplementedShippingServiceServer) CalculateCost(context.Context, *ShippingCostRequest) (*ShippingCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateCost not implemented")
}
func (UnimplementedShippingServiceServer) InputTrackingNumber(context.Context, *InputTrackingRequest) (*ShipmentDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InputTrackingNumber not implemented")
}
func (UnimplementedShippingServiceServer) GetShipmentStatus(context.Context, *GetShipmentStatusRequest) (*ShipmentDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipmentStatus not implemented")
}
func (UnimplementedShippingServiceServer) Create(context.Context, *CreateShipmentRequest) (*ShipmentDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedShippingServiceServer) mustEmbedUnimplementedShippingServiceServer() {}
func (UnimplementedShippingServiceServer) testEmbeddedByValue()                         {}

// UnsafeShippingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShippingServiceServer will
// result in compilation errors.
type UnsafeShippingServiceServer interface {
	mustEmbedUnimplementedShippingServiceServer()
}

func RegisterShippingServiceServer(s grpc.ServiceRegistrar, srv ShippingServiceServer) {
	// If the following call pancis, it indicates UnimplementedShippingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShippingService_ServiceDesc, srv)
}

func _ShippingService_CalculateCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShippingCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CalculateCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_CalculateCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CalculateCost(ctx, req.(*ShippingCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_InputTrackingNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputTrackingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).InputTrackingNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_InputTrackingNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).InputTrackingNumber(ctx, req.(*InputTrackingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_GetShipmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetShipmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_GetShipmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetShipmentStatus(ctx, req.(*GetShipmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShippingService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).Create(ctx, req.(*CreateShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShippingService_ServiceDesc is the grpc.ServiceDesc for ShippingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShippingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shipping.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateCost",
			Handler:    _ShippingService_CalculateCost_Handler,
		},
		{
			MethodName: "InputTrackingNumber",
			Handler:    _ShippingService_InputTrackingNumber_Handler,
		},
		{
			MethodName: "GetShipmentStatus",
			Handler:    _ShippingService_GetShipmentStatus_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ShippingService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shipping.proto",
}
